language: node_js
node_js: 
  - node

env:
  global:
    - PATH=$HOME/.local/bin:$PATH

script: node print.js site/index.html site/pyramids.pdf

deploy:
  - provider: releases
    skip_cleanup: true
    on:
      tags: true
    api_key: $GITHUB_API_KEY
    file: 
      - site/pyramids.pdf
  - provider: script
    on:
      branch: master
    skip_cleanup: true
    script: "bash deploytf.sh"
  - provider: s3
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: gjhr.me
    skip_cleanup: true
    local_dir: site
    region: eu-west-1
  - provider: script
    on:
      branch: master
    skip_cleanup: true
    script: "pip install --user awscli && aws cloudfront create-invalidation --distribution-id E3AI95P0PTTR3D --paths '/*'"